### ISSUE TITLE
1.14.4 Server not loading

### ISSUE THREAD

**Issue by Wissi** [McJtyMods/RFToolsBase#1]
Thanks for your great work.

We are seeing your mod in the server's crash.
Full Crash log [here](https://gist.github.com/Wissi/a9aa3a4bea376ceb59561b29219c19fd).
Full debug.log [here](https://gist.github.com/Wissi/5c208ef6560ff065c2626f368cd96cad).

Will readd to our modpack as soon as it's ready.
Thanks.

**Comment by McJty** [comment]
Do you have mcjtylib?

**Comment by Wissi** [comment]
Yes and I just noticed that it was "disabled".
Enabling it and all is working fine.

Thank you so much. 
I will now close it due to my mistake.
