### ISSUE TITLE
[Question][1.18.2]Is it normal that the button screen module on the screen cannot be clicked on the tablet(screen)?

### ISSUE THREAD

**Issue by ghost** [McJtyMods/RFToolsBase#102]
As the title, is it normal that the button screen module on the screen cannot be clicked on the tablet(screen)?
I hope to be able to click the button on the tablet.

![2023-11-27_23 04 16](https://github.com/McJtyMods/RFToolsBase/assets/115923988/f416cf5d-71bf-46cf-9c71-f9b3e59bba84)

**Comment by McJty** [comment]
Looking at this

**Comment by McJty** [comment]
Fixed in 1.18, 1.19.2, and 1.20.1

**Comment by McJty** [comment]
In RFToolsUtility btw

**Comment by ghost** [comment]
> Fixed in 1.18, 1.19.2, and 1.20.1

Thank you!
I tested it and it runs very well.
