### ISSUE TITLE
RFtools Tablet Cann't remote access Storage Scanner

### ISSUE THREAD

**Issue by maple32768** [McJtyMods/RFToolsBase#103]
Modpack:
FTB Presents Direwolf20 1.20

Modpack version:
1.7.0

Describe the bug:
After Link Storage Control Screen Module to the Storage Scanner, and insert into Tablet.
i cann't remote access Storage Scanner,nothing happend.

Steps to reproduce:
1. Shift right click Storage Scanner with Storage Control Screen Module.
2. Shift right click Tablet.
3. Put Storage Control Screen Module on empty slot.
4. Esc.
5. Right clict Tablet.

Expected behaviour:
Open Linked Storage Scanner Interface.

**Comment by McJty** [comment]
Wrong mod. This is for rftools storage. Also already reported (see here: https://github.com/McJtyMods/RFToolsStorage/issues/82#issuecomment-1828281690)
In addition it's not a problem with my mod but with another mod. See that issue
