### ISSUE TITLE
[1.15.2] Wrong Nether Dimensional Shard Ore Texture

### ISSUE THREAD

**Issue by TheUntamed** [McJtyMods/RFToolsBase#11]
The Netherrack Texture in MC 1.14+ is different than in 1.12. The Dimensional Shard Ore has still the old texture:

![Screenshot_1](https://user-images.githubusercontent.com/48363903/78693331-641d7d00-78fb-11ea-816f-f0ff8556addc.jpg)

**Comment by nasmal** [comment]
The texture is [here](https://github.com/McJtyMods/RFToolsBase/blob/master/src/main/resources/assets/rftoolsbase/textures/block/ores/dimensionalshard_nether.png), perhaps you can change it and submit a PR?

**Comment by Jkosio23** [comment]
Still wrong, two years later.

**Comment by McJty** [comment]
It will get fixed. The PR for this was merged. Just didn't have a chance to release it yet
