### ISSUE TITLE
[1.20.1] How to remove dim shards generation from nether and overworld?

### ISSUE THREAD

**Issue by Exzept1on** [McJtyMods/RFToolsBase#114]
Maybe I'am blind, but I cant see some config for that
Installed mods:
![image](https://github.com/user-attachments/assets/fe586553-0ecd-4108-9934-a2e6dc08a94d)

**Comment by McJty** [comment]
That's because that can no longer be configured. You'll have to remove them using a custom datapack which replaces the ore generation done by rftoolsbase

**Comment by Exzept1on** [comment]
thanks, solves my issue
