### ISSUE TITLE
Filter Module will not stay in blacklist mode

### ISSUE THREAD

**Issue by lafflam** [McJtyMods/RFToolsBase#116]
While playing the ATM10 modpack, I found that the Filter Module will not stay in blacklist mode. After selecting blacklist mode and adding some blocks like c:stones, I exit the Filter Module gui, then re-open the gui to find the filter has reverted back to whitelist mode. In fact all of the buttons (D, N, and M) revert back when exiting the Filter gui.

To test this, outside of the ATM10 modpack, I created a clean new Neoforge Minecraft instance with only the following in order to eliminate cross-mod incompatibilities:

Minecraft 1.21.1
NeoForge 21.1.85
McJtyLib 1.21-9.0.5
RFToolsBase 1.21-6.0.2
RFToolsPower 1.21-7.0.1
RFToolsBuilder 1.21-7.0.0

I looked through the configs and could not find anything that looked like a setting that would prevent blacklist mode from working as expected.

Setting Blacklist mode:
![2024-12-09_18 45 30](https://github.com/user-attachments/assets/1d72f775-55a2-4b98-81f9-37567f2852b0)

After closing and reopening gui, it reverts back to whitelist mode:
![2024-12-09_18 45 36](https://github.com/user-attachments/assets/6b54522d-9760-4571-81bd-d7a26a3269d5)

(edited for typos, sorry)

**Comment by McJty** [comment]
Will be fixed next version
