### ISSUE TITLE
Inventory clears on a chunk reload [1.21.1]

### ISSUE THREAD

**Issue by Necrocaustic** [McJtyMods/RFToolsBase#117]
Hello,
I was using the infuser in All The Mods 10, and when I went to the nether and came back, the inventory of the infuser was cleared.
Did some further testing and it looks like the machine state is reset to empty (0 power / no items) every time the chunk is unloaded and reloaded, either by dimension travelling or by teleporting away.
Machine does _not_ do this when F3+A is used to reload chunks, but whether that is because of optimizations made by other mods within ATM10, I don't know.
Does consistently trigger the issue on dimension change or player moving far away. 
Can provide video if needed.
Thank you.

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Will be fixed next version
