### ISSUE TITLE
Builder (quarry) not working in 1.15 server

### ISSUE THREAD

**Issue by IronLeo03** [McJtyMods/RFToolsBase#12]
I'm trying to use the builder as a quarry (using the quarry card) in a server but doesn't mine blocks.
I have tried to do that in single player and it does work.

**Comment by McJty** [comment]
I need a LOT more information then this. Exact version of RFTools Builder, what other mods are on the server. Is there some kind of protection mod. What is in the logs.

**Comment by IronLeo03** [comment]
I solved.
Apparently ftb chunks, unlike older version, does block quarry.
Fun fact: Computer craft's turtle ignores claim so I didn't think about those while I changed it.
Thank you and have a good day.
