### ISSUE TITLE
Builder + Shape Card Offset not working properly

### ISSUE THREAD

**Issue by Leaderofarmies** [McJtyMods/RFToolsBase#17]
So pretty much the issue is with the following situation
I have a Builder block, with a shape card (clearing quarry).
The preview shows that it will mine the area that I want, but what happens it that it will randomly mine certain blocks from an area that it would mine without an offset. It seems to be just random as the blocks that it mines outside the area is varied

**Comment by McJty** [comment]
NEVER forget to mention the versions please. Also this is reported to the wrong github. Should be put in the RFToolsBuilder github if it is for 1.15 or RFTools github if it is for 1.12
