### ISSUE TITLE
[1.15.2] Only a very small subset of the mod is showing?

### ISSUE THREAD

**Issue by jarquafelmu** [McJtyMods/RFToolsBase#19]
Just installed RFToolsBase into my world but only a very small set of the mod is available, I had thought from the description and from the issues here that more of it was implemented?
![image](https://user-images.githubusercontent.com/5807272/90779920-718c4000-e2bb-11ea-9b54-d5eb6fcbed77.png)

RFToolsBase v1.1.3-beta
McJtyLib v4.1.4

**Comment by McJty** [comment]
As discussed
