### ISSUE TITLE
Coal Generator cannot be infused

### ISSUE THREAD

**Issue by NillerMedDild** [McJtyMods/RFToolsBase#2]
Hey o/

One of my players reported that the Coal Generator cannot be infused with the Machine Infuser

### Versions
- rftoolsbase-1.14-0.0.5-alpha
- Forge-1.14.4-28.1.39

**Comment by RudiHansen** [comment]
I also have that problem on https://github.com/FTBTeam/FTB-Unstable-1.14

**Comment by daniel-for-github** [comment]
mc 1.14.4 forge , forge-1.14.4-28.1.45 , rftoolsbase-1.14-0.0.6-alpha
back from factorio 
the infuser  is at the moment a refuser, not taking any machine
 
tis is just a info, you are doing a great job, and i can imagine how much work the portation will be

powercells and builder working great, i load the powercells with SolarGeneration-1.14.4.-1.1.0 solar panels, ( with modified recipes) 

regards

**Comment by McJty** [comment]
yes I know. I actually forgot about this bug. Will be for next release :-)

**Comment by McJty** [comment]
Ha, funny bug. The infuser would work fine on blocks that are already partially infused. Problem is: how to get the initial infusion started :-)
