### ISSUE TITLE
Can you compile a 1.16.1 version

### ISSUE THREAD

**Issue by Killer-Awesome-Phantom** [McJtyMods/RFToolsBase#20]
Can you make a 1.16.1 version if it not too much work to back port it as most other mods are still on 1.16.1 and the twitch launcher can even make an 1.16.2 instance of minecraft yet?

**Comment by McJty** [comment]
I'm sorry but I'm afraid that is a lot of work for me. I'm already depending on latest forge. I would also need additional maven repositories for my library mods and it would be a nightmare to do all of this. So I think you better wait until twitch is ready for 1.16.2 or else use another launcher
