### ISSUE TITLE
1.15.2 CTD Using RF Tools

### ISSUE THREAD

**Issue by MokahTGS** [McJtyMods/RFToolsBase#22]
Trying to load we get a CTD.

Crash Log: https://pastebin.com/WJixFsQb

Full mod list: https://pastebin.com/zpQyK2k6

MC 1.15.2
Forge 31.2.33
mcjtylib-1.15-4.1.7.jar
theoneprobe-1.15-2.0.7.jar
rftoolsbase-1.15-1.1.6.jar
rftoolsbuilder-1.15-2.1.8.jar
rftoolscontrol-1.15-3.0.7.jar
rftoolspower-1.15-2.2.4.jar
rftoolsstorage-1.15-1.1.9.jar
rftoolsutility-1.15-2.1.5-beta.jar

**Comment by McJty** [comment]
Make sure all mods are latest version. RFTools Utility for example is not latest

**Comment by MokahTGS** [comment]
odd that it was not coming up as a mod that needed to be updated in the GDLauncher.
