### ISSUE TITLE
crash and world corrupted after placing a blaze syringe into rftools mob spawner

### ISSUE THREAD

**Issue by TheYoloPanda** [McJtyMods/RFToolsBase#23]
https://paste.ee/p/bYBPl
After placing the syringe into the spawner the game crashed. i restarted it and loaded the world and it instantly crash.

**Comment by McJty** [comment]
Can you use another paste site? I can't visit paste.ee. My ISP blocks it

**Comment by McJty** [comment]
Also what version?

**Comment by TheYoloPanda** [comment]
Crashes 2/2 times.
https://pastebin.com/2B0wRxb1
the world gets corrupted 100% - 2/2 times
https://pastebin.com/ev2JD55x

rftoolsbase-1.16-2.0.5
rftoolsbuilder-1.16-3.0.7
rftoolscontrol-1.16-4.0.5
rftoolspower-1.16-3.0.7
rftoolsstorage-1.16-2.0.5
rftoolsutility-1.16-3.0.9

**Comment by McJty** [comment]
I will check it out

**Comment by McJty** [comment]
What did the syringe contain? For what mob?

**Comment by TheYoloPanda** [comment]
Blaze

**Comment by McJty** [comment]
A normal vanilla blaze? Not modded? That's strange. Can you show the syringe tooltip?

**Comment by TheYoloPanda** [comment]
![image](https://user-images.githubusercontent.com/42820115/95352084-2a392d80-08c2-11eb-8f44-acdd872c2a22.png)

**Comment by McJty** [comment]
I'm not sure why it wasn't working but in the latest version that I just released it should no longer cause a crash

**Comment by TheYoloPanda** [comment]
i will update and check

**Comment by TheYoloPanda** [comment]
Yeah you fixed it! ty
