### ISSUE TITLE
Filter completely broken

### ISSUE THREAD

**Issue by Darkere** [McJtyMods/RFToolsBase#24]
-Cannot add tags.
-Cannot remove anything.
-Rendering is broken:
![image](https://user-images.githubusercontent.com/4283717/96494854-3371b500-1247-11eb-8ae2-256c6fbe1145.png)

Pressing expand crashes the client:
https://gist.github.com/Darkere/90d0b8f6e526f3d54de8de2310c13e7a

Forge 1.16.3 34.1.23
Rftools base: rftoolsbase-1.16-2.0.5.jar

**Comment by McJty** [comment]
I can reproduce. Testing now

**Comment by McJty** [comment]
Should be fixed now. Releasing updates at this moment
