### ISSUE TITLE
Tablet deleting modules when trying to switch between them.

### ISSUE THREAD

**Issue by stanisshap** [McJtyMods/RFToolsBase#25]
In version 1.16.3, 2.0.6.

With any modules in the tablet, when trying to switch to a empty space or other module all modules disappear. Using the brackets to switch between modules does nothing. Remapping the brackets to other keys also does nothing.

here is a video : [Video link](https://imgur.com/a/SOfxBtE)

**Comment by McJty** [comment]
I cannot reproduce this at all. Do you have any other mods installed? Can you reproduce this with just RFTools mods alone?

**Comment by stanisshap** [comment]
nope, just RFtools seems to work fine. Also with Jei it works normal. I was playing with All the mods modpack so I guess the possibilities for conflict are endless. I guess I could manually go through every single mod and check if it recreates the issue.

Is there any sense in doing this or could there be multiple mods together that cause this issue?

Thanks.

**Comment by McJty** [comment]
This might be useful. One way to do it faster is to do this with batches of mods. i.e. 10 or 20 mods at a time

**Comment by stanisshap** [comment]
.... I added all the mods in groups of ten and could not recreate the problem. I then reinstalled the whole mod pack and the issue was also gone. Then I went back to my old mod pack installation where the issue was present... and the issue was no longer occurring. Very weird problem, sorry for taking your time, and thanks for responding!
