### ISSUE TITLE
Dimensional Shards Not generating in 1.16

### ISSUE THREAD

**Issue by ZapDragon** [McJtyMods/RFToolsBase#28]
Versions:
`
Minecraft 1.16.3
Forge 1.16.3-34.1.25
rftoolsbase-1.16-2.0.6
`

MinecraftServer/world/serverconfig/rftoolsbase-server.toml

`
#Settings for the infusing system
[infuser]
        #Maximum RF storage that the infuser can hold
        #Range: > 0
        infuserMaxRF = 60000
        #RF per tick that the infuser can receive
        #Range: > 0
        infuserRFPerTick = 600
        #Maximum amount of dimensional shards before a machine is fully infused
        #Range: > 1
        maxInfuse = 256
        #Amount of RF used per tick while infusing
        #Range: > 0
        usePerTick = 600
#Dimensional shard ore generation
[worldgen]
        #Overworld
        [worldgen.nether]
                #Number of times to try generate the ore (set to 0 to disable)
                #Range: 0 ~ 256
                oreChances = 12
                #Max height
                #Range: 0 ~ 256
                oreMax = 126
                #Max size of veins
                #Range: 1 ~ 256
                oreVeinsize = 16
                #Min height
                #Range: 0 ~ 256
                oreMin = 2
        #Overworld
        [worldgen.overworld]
                #Number of times to try generate the ore (set to 0 to disable)
                #Range: 0 ~ 256
                oreChances = 2
                #Max height
                #Range: 0 ~ 256
                oreMax = 60
                #Max size of veins
                #Range: 1 ~ 256
                oreVeinsize = 7
                #Min height
                #Range: 0 ~ 256
                oreMin = 2
`

The above file is created by RFTools base.

I have deleted my nether dimension Multiple times and regenerated it, and even setup an X-Ray in an attempt to confirm that the dimensional shard ore was generating.

I also moved the above config file to MinecraftServer/configs to see if that would help.

This ore will not generate anywhere. Overworld or Nether.

Edit: Apologies for the Code formatting above. Github breaks it.

**Comment by McJty** [comment]
Yes, this is not implemented yet in 1.16. Always forget to do this. Thanks for reminding me :-)

**Comment by McJty** [comment]
Will be fixed next release
