### ISSUE TITLE
F1 for help doesn't work from JEI

### ISSUE THREAD

**Issue by aaronhowser1** [McJtyMods/RFToolsBase#29]
![image](https://user-images.githubusercontent.com/15698722/101238917-20a52980-36a9-11eb-9070-e4d6cd21b2e3.png)
![image](https://user-images.githubusercontent.com/15698722/101238920-2ac72800-36a9-11eb-9987-bf8a02b2571d.png)
F1 is already a vanilla keybind to hide your UI.

**Comment by McJty** [comment]
Hmm strange. Works fine for me

**Comment by aaronhowser1** [comment]
Apparently it just doesn't work from JEI, nothing to do with keybind conflicts. The item just has to be in your inventory, which makes sense.

**Comment by McJty** [comment]
Actually I can get it to work from within JEI too

**Comment by aaronhowser1** [comment]
In that case I'll reopen it and change the name lol

**Comment by McJty** [comment]
Well it works fine. Just make sure the search bar on the bottom is not selected and then it will work Just tested it:
![image](https://user-images.githubusercontent.com/8188472/102312349-d5bfc780-3f6e-11eb-8b25-70b97cdce6be.png)
