### ISSUE TITLE
Crash when clicking on Builder with Smart Wrench

### ISSUE THREAD

**Issue by MelanX** [McJtyMods/RFToolsBase#3]
Forge: 28.1.79
RFTools Base: 1.14-0.0.7-alpha
RFTools Builder: 1.14-1.2.6-alpha
Crash log: https://pastebin.com/pMsFwgPw

I clicked on the left side with smart wrench on the builder. Game instantly crashed.

**Comment by McJty** [comment]
Will be fixed next release. Sorry for long delay
