### ISSUE TITLE
After updating to the latest version, Ore Gen will not disable after disabling it in the server config

### ISSUE THREAD

**Issue by BedrockLegends** [McJtyMods/RFToolsBase#30]
I am trying to disable ore gen for a sky pack for 1.16.4+

**Comment by McJty** [comment]
How exactly? What are you doing?

**Comment by BedrockLegends** [comment]
[rftoolsbase-server.zip](https://github.com/McJtyMods/RFToolsBase/files/5650783/rftoolsbase-server.zip)

**Comment by McJty** [comment]
I'll check it out. Note that this never worked as in the previous version there simply was no oregen :-)

**Comment by BedrockLegends** [comment]
okay, I mainly just need the ore gen gone for a sky pack

**Comment by McJty** [comment]
Hmm why is this important for a sky pack given that there is nothing for the ore to generate in?

**Comment by BedrockLegends** [comment]
cause of the Nether and End that ores still gen in

**Comment by McJty** [comment]
Why did you close this? Was the problem resolved?

**Comment by jinkhya** [comment]
Hello! I can confirm that disabling the oreChances to 0 doesn't prevent the ores to spawn :) 

rftoolsbase-server.toml (in defaultconfigs and world/serverconfig :
https://i.imgur.com/j3tdjzK.png
fresh world : 
https://i.imgur.com/EJSocmV.png
