### ISSUE TITLE
[1.16.4] Cannot disable worldgen.

### ISSUE THREAD

**Issue by curlywaffles** [McJtyMods/RFToolsBase#32]
I may or may not be doing this wrong but from what I can tell you change the worldgen in the default config. I have everything set to 0 on the nether and overworld worldgen and the Dimensional Shard Ore still spawns.

rftoolsbase-1.16-2.0.9
forge 35.1.13

**Comment by NielsPilgaard** [comment]
I can confirm this, both server and singleplayer.

**Comment by mattheufarmer** [comment]
I'm having the same problem.

**Comment by McJty** [comment]
What config file are you changing? Using latest of rftoolbase?

**Comment by NielsPilgaard** [comment]
This was fixed a while ago, I can confirm :)

**Comment by mattheufarmer** [comment]
I'm using rftoolsbase-1.16-2.0.9.

The config I'm using is rftoolsbase-server.toml which I have put in the defaultconfigs folder of my instance.

Here's a sample of the config file. 

`#Overworld
	[worldgen.overworld]
		#Number of times to try generate the ore (set to 0 to disable)
		#Range: 0 ~ 256
		oreChances = 0
		#Max size of veins
		#Range: 1 ~ 256
		oreVeinsize = 1
		#Min height
		#Range: 0 ~ 256
		oreMin = 0
		#Max height
		#Range: 0 ~ 256
		oreMax = 0
`

With all this, I'm still finding large groups of Dimensional Shard Ore.

*checks curseforge*
*sees 2.0.10*
*sees changelog for 2.0.10*
*hangs head in shame for not checking*

This is what I get for basing my personal pack on Dire's pack and assuming it has the newest versions of mods. My bad.

**Comment by McJty** [comment]
No problem :-)
