### ISSUE TITLE
F1 for help disables your UI

### ISSUE THREAD

**Issue by aaronhowser1** [McJtyMods/RFToolsBase#35]
![image](https://user-images.githubusercontent.com/15698722/103932011-d8818880-50e6-11eb-975e-d67d9e2588f0.png)
Press F1
![image](https://user-images.githubusercontent.com/15698722/103932016-db7c7900-50e6-11eb-92ad-0f72e5c8e94d.png)
Press Escape
![image](https://user-images.githubusercontent.com/15698722/103932033-e1725a00-50e6-11eb-8e56-162aee169b90.png)

`rftoolsbase-1.16-2.0.9`

**Comment by Esmerald1no** [comment]
Pressing F1 to disable the UI is a Minecraft vanilla feature. while I agree that it is certainly an inconvenient choice of help key, you can always re-enable the UI by pressing F1 once more

**Comment by McJty** [comment]
The F1 key for the manual can be changed in the key control section. So change it if you want another key
