### ISSUE TITLE
Builder Carry problem

### ISSUE THREAD

**Issue by XiaoSawk** [McJtyMods/RFToolsBase#40]
Rftoolsbuilder-1.16-3.0.13

Modpack : Valhelsia 3 - 1.16.5 - v3.1.6 (with some mod self added, like rftool)

On server :

When i turn on the builder with the shape card (quarry), he destroy nothings

Solo : 

Everything work perfectly.

**Comment by McJty** [comment]
This is usually caused by claimed chunks. The claim utility needs to allow fake players

**Comment by XiaoSawk** [comment]
Yeah , minecolonies shit. thanks for help

**Comment by tyler489** [comment]
Minecolonies has a "policy" that the block that does the mining should "emulate" the player that placed it. 
```Please report to IF to handle their fakeplayers accordingly. Fakeplayers are supposed to hold the UUID of the player that placed them, that is how we also designed the initial compatibility. The + is only a workaround to allow players to handle that while those mods are denying their responsibility to handle the fakeplayers accordingly.```
Taken from
https://github.com/ldtteam/minecolonies/issues/6375

**Comment by McJty** [comment]
I have implemented this feature for the next version
