### ISSUE TITLE
[1.16.5] Empty crafting cards do not stack

### ISSUE THREAD

**Issue by Deepresonance2021** [McJtyMods/RFToolsBase#41]
Empty crafting cards do not stack if for some reason they are separated in the inventory.

Btw did not mention it in the first issue i reported, but thank you McJty for great mods and your hard work.
   
    • Forge: 1.16.5-36.0.40
    • McJtyLib: 1.16-5.0.16
    • RFTools base: 1.16-2.0.10

**Comment by McJty** [comment]
Max stacksize is 1 for those. Intentional
