### ISSUE TITLE
Builder Bugs

### ISSUE THREAD

**Issue by tyler489** [McJtyMods/RFToolsBase#44]
The "highlight" current position option in the builder gui does not seem to be functioning on servers in 1.16.5.

 The Pump and quarry card seems to ignore certain liquids such as Allthemodium soul lava, although thats probably on them. 
 
 I Thought the "move entity" option was supposed to pick up items that were dropped in the world from things like chests but it does not seem to be doing that with a quarry card.
 
mcjtylib-1.16-5.0.19
Base 2.0.10
Builder3.0.16
Control 4.0.8
Power 3.0.8
Storage 2.0.11
Utilities 3.0.25

Playing ATM6 Sky v 1.0.5

**Comment by McJty** [comment]
'Move entity' is only for the space chamber which doesn't exist on 1.16.5 yet. The 'current' position should work. But do you have optifine or something?

No idea on the liquids. What mod adds that soul lava?

**Comment by tyler489** [comment]
I do not have Optifine or Optiforge. I have tried 3 or 4 different packs now and it has never shown up.
Soul Lava is added by AllTheModium.
https://www.curseforge.com/minecraft/mc-mods/allthemodium

**Comment by McJty** [comment]
And does it have any kind of per-player restriction or anything? Can any player simply pick up the liquid?

**Comment by tyler489** [comment]
Yes, 'Im checking to see if they blocked fake players perhaps
