### ISSUE TITLE
dropping RF energy for FE

### ISSUE THREAD

**Issue by darkt1981** [McJtyMods/RFToolsBase#45]
Hi there first off love your mods,

there seems to be just one small issue, most mods do not support RF energy anymore and they seems to all switch over to FE energy, now if seens a few time's where some items dont wanna work together when powered. Seeing they both need diffrent Power forms.

Could you add like a FE - RF adaptor/converter or change all rf to FE like most mods seem to be doeing now a days.

Thanks in advance.

**Comment by McJty** [comment]
RF and FE are the same thing

**Comment by McJty** [comment]
And my mods are fully compatible with all other mods that support RF/FE. At least if they do it right. I know my mods work with Mekanism, Thermal Expansion, ...
