### ISSUE TITLE
Information Screens font too dark.

### ISSUE THREAD

**Issue by winsrp** [McJtyMods/RFToolsBase#46]
If I put the information screen (rftools base) or a screen with a screen module (rftools utility), the font seems too dark and can barely be read.

On the screen menu, there is a bright mode, which fixes this, but the information screen doesn't have this option.

Thanks.

**Comment by McJty** [comment]
Hmm seems to be ok to me?

![image](https://user-images.githubusercontent.com/8188472/116971841-757db800-acba-11eb-973f-3d8252e770c6.png)

**Comment by winsrp** [comment]
weird, I used it with normal minecraft and it looked a bit dark all around, now that I'm playing with optifine and shaders it still looks dark, but only during the day, at night it looks great. X-net gives an open gl error with the connectors, but I suppose you don't support using optifine, lots of modders don't, but most probably is an optifine issue anyway.

Tx, you are the best McJty!
