### ISSUE TITLE
Make 1.16 the default branch

### ISSUE THREAD

**Issue by ochotonida** [McJtyMods/RFToolsBase#48]
Currently, the 1.14 branch is the default branch. Since people who would want to make PR's or browse the repository are likely looking for the 1.16 branch, it would make sense to make this the default branch. Because the 1.14 branch is called 'master', it's also not immediately clear that this is not the latest version of the mod. (this issue applies to your other repositories as well).

**Comment by McJty** [comment]
Fixed some time ago
