### ISSUE TITLE
Rare crash when clicking Filter buttons

### ISSUE THREAD

**Issue by NielsPilgaard** [McJtyMods/RFToolsBase#52]
I was trying to delete a few entries from a Filter, accidentally clicked expand tag, and I crashed.

This happened after using the Filter on and off without issues for about 10 minutes

https://gist.github.com/NillerMedDild/c3b3ecaeb0f3781c4f5689e2850290f3

**Comment by McJty** [comment]
That gist doesn't exist. Is this still relevant?

**Comment by NielsPilgaard** [comment]
Hopefully not, it was a transient issue anyway 😄
