### ISSUE TITLE
Suggestion : Untraversable Block for Elevators

### ISSUE THREAD

**Issue by ExDomino** [McJtyMods/RFToolsBase#54]
Hello,

My idea is creating an untraversable block that if placed between two elevator controller, the elevator would refuses to travel between these two floors. Useful for example for placing an elevator inside a SecurityCraft base and preventing anyone to get inside the base in creating a new floor and use the elevator to enter/exit. This block should be placed at the same coordinate than elevator floor controlers.

Thank you in advance!

**Comment by McJty** [comment]
Elevator is for 1.12 and I no longer develop on 1.12
