### ISSUE TITLE
Modular Storage : * to craft 64

### ISSUE THREAD

**Issue by ExDomino** [McJtyMods/RFToolsBase#55]
Hello,

In the Modular Storage, the * button is used to craft 64, but * looks like X and some players can think that button clear the crafting area. Can you change the text on this button please? And a clean crafting area button should be appreciated too.

Thank in advance.

**Comment by McJty** [comment]
Right clicking the craft result should clear it

**Comment by ExDomino** [comment]
Ok thanks, but I still click on the * button by error.
