### ISSUE TITLE
Want a little help with the Patchouli Guidebook?

### ISSUE THREAD

**Issue by wrincewind** [McJtyMods/RFToolsBase#56]
Hi there! I hope this isn't presumptuous or anything, but i helped make the Blood Magic Guidebook along with VT-14, and i noticed the RFTools one could use a little love.

I saw that 'think about the new manual system' was in your TODO, so I thought i'd ask before getting stuck in - how would you feel about me submitting a PR with some more extensive documentation?

**Comment by McJty** [comment]
I would love that!

**Comment by wrincewind** [comment]
OK! 
so, I'm doing a little dinking around right now, setting up a workspace, trying to work out which all of your mods have manuals (and which ones don't yet that you'd like to!) 

It looks like the recommended way to do so is via MultiWorkspace, correct? 

Secondly, do you have any preference between setting the manual up as one big book in RFToolsBase, with checks for the presence of the other mods, or would you rather have each mod extend the main manual from within themselves? 

It's mostly an organisational thing, but i slightly prefer the former as it lets you check up on entries for mods you haven't currently got loaded in your workspace.

**Comment by McJty** [comment]
Hmm why not do it like it's already working right now?

And yes. The multi workspace is the best approach

**Comment by McJty** [comment]
We are going to switch to guidebook so this is no longer relevant
