### ISSUE TITLE
Crash Screen capability null. 

### ISSUE THREAD

**Issue by Darkere** [McJtyMods/RFToolsBase#58]
https://gist.github.com/Darkere/6917f003a6265a24c68940321091c17f

Screens seem to be crashing due to the capability being invalid. 

https://gist.github.com/Darkere/abd3ba87c436e1e0fec460ec0873be3f
Second crash is from another user. He claims he fixed it by removing everything but RFtoolsbase?

forge-1.16.5-36.2.4.jar
rftoolsbase-1.16-2.0.11.jar                      
xnet-1.16-3.0.13.jar                            
rftoolspower-1.16-3.0.9.jar                       
rftoolsbuilder-1.16-3.1.2.jar                    
rftoolsstorage-1.16-2.0.13.jar                   
rftoolscontrol-1.16-4.0.11.jar

**Comment by McJty** [comment]
That first crash seems to be a problem in cyclopscore though:

	at org.cyclops.cyclopscore.modcompat.capabilities.DefaultCapabilityProvider.getCapability(DefaultCapabilityProvider.java:42) ~[cyclopscore:1.11.9] {re:classloading}

**Comment by Darkere** [comment]
Cyclops core crashes because it specifically catches the capability being null. Otherwise, this would crash a bit later as the capability is present but null. Second crash is the same. 

https://github.com/CyclopsMC/CyclopsCore/issues/164

**Comment by McJty** [comment]
I know what's wrong. Will fix soon

**Comment by McJty** [comment]
Fixed some time ago
