### ISSUE TITLE
Dimensions: Block Absorber

### ISSUE THREAD

**Issue by Ragelyna** [McJtyMods/RFToolsBase#60]
Currently, Block Absorber is not absorbing blocks.
Modpack: Enigmatica 6 (1.16.5)
Mod Version: 1.16-7.0.15-beta
![Screenshot_2](https://user-images.githubusercontent.com/40332465/139700448-8c278969-56de-4689-8708-170fc3da1b01.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/40332465/139700450-5c684c4b-5f0d-4881-b77b-d473cafa2c1f.jpg)

**Comment by McJty** [comment]
Wrong issue tracker and should be ok now
