### ISSUE TITLE
Machines lose state of inserted items

### ISSUE THREAD

**Issue by enigmaquip** [McJtyMods/RFToolsBase#65]
Breaking an infuser with something inside of it does not drop the item nor keep the item in inventory, it's lost
Breaking a builder the inserted card is lost.

This may be related to a change mentioned by another mod dev:

> mojang changed how tiles save data

> in 1.17 and lower, you would override the save function, in 1.18 save still exists, but you need to override saveAdditional

> its `CompoundTag save(CompoundTag tag)` vs `void saveAdditional(CompoundTag tag)`

https://github.com/BiggerSeries/BiggerReactors/commit/07e7277f9a7cb8d24cdcfdd4110882ef55041d60

**Comment by McJty** [comment]
Fixed now
