### ISSUE TITLE
Mouse Clicking outside the Filter Window causes a crash (1.18.1)

### ISSUE THREAD

**Issue by enigmaquip** [McJtyMods/RFToolsBase#67]
You can escape out of the filter screen fine, but mouse clicks outside are not

forge 39.0.10
mcjtylib-1.18-6.0.5
rftoolsbase-1.18-3.0.1

https://pastebin.com/ffkLzB4U

**Comment by McJty** [comment]
I can reproduce this and I'll fix this in the next release

**Comment by jeremiahwinsley** [comment]
This issue is also present on 1.16.5.

**Comment by DizzyDJW** [comment]
Also present in 1.19.2 version
