### ISSUE TITLE
The Builder is more obnoxious than useful.

### ISSUE THREAD

**Issue by SoftGuardian** [McJtyMods/RFToolsBase#68]
Literally everytime I set it's offset it changes itself to 25 5 25 whatever I do it's just gonna revert back, of course excluding that the preview blocks stay there and right clicking do nothing.. I hope to see new mods rather than this buggy mess

**Comment by McJty** [comment]
What version? Can you describe in more detail what you're doing?

**Comment by MrSam76** [comment]
I can confirm this using 1.16-3.1.5 using the preview button creates blocks that originate from the builder and persist even after turning off preview. If you use the ? button in the builder, it sometimes, not always, resets the co-ords.

**Comment by McJty** [comment]
hmm weird. I'll see if I can find it but I have never been able to reproduce these problems

**Comment by SoftGuardian** [comment]
Even though I spent 2 hours cleaning the preview blocks, It ended up placing the blocks where I wanted to but still the preview is broken. I'm playing FTB OceanBlock 1.11.0

**Comment by McJty** [comment]
I'm currently busy porting Deep Resonance. After that is done I'll come back to this and see if I can get this to be more stable

**Comment by McJty** [comment]
Should be better now

**Comment by Kangy1103** [comment]
@McJty I seem to have a variation of this issue, would you like me to post my stuff here or make a new issue?

**Comment by McJty** [comment]
Perhaps make a new one. Thanks
