### ISSUE TITLE
[1.18.1] Builder Crash Previewing Space Card

### ISSUE THREAD

**Issue by enigmaquip** [McJtyMods/RFToolsBase#69]
Clicking Preview in the Builder with an active space card causes client crash

mcjtylib-1.18-6.0.8.jar
rftoolsbase-1.18-3.0.4.jar
rftoolsbuilder-1.18-4.0.5.jar

[Crash Log](https://pastebin.com/6uM4aUJ0)

**Comment by McJty** [comment]
Old bug
