### ISSUE TITLE
1.16.5 GUI filter crash

### ISSUE THREAD

**Issue by abint** [McJtyMods/RFToolsBase#70]
Minecraft: 1.16.5
Forge: 36.2.23
RFToolsBase: 1.16-2.1.2
Pack: All The Mods 6 
Exiting the GUI for the filter can crash the client. I've experienced it after quickly exiting after adding a new item to the filter.

Crash log: https://pastebin.com/rypTqP2V

Similar to issue 67, but the log trace is definitely different

**Comment by Snownee** [comment]
Can confirm this. Same stacktrace

**Comment by McJty** [comment]
Will fix this in a moment
