### ISSUE TITLE
Infuser not working (All the Mods 7)

### ISSUE THREAD

**Issue by Mohawk1025** [McJtyMods/RFToolsBase#78]
I'm playing on All the Mods 7 and I'm having a puzzling issue with the infuser. I can't put any machines into the machine slot. I can't find any config file where the infuser is disabled, either.

**Comment by McJty** [comment]
What version?

**Comment by Mohawk1025** [comment]
> 

ATM7 0.4.9

rftoolsbase 1.18-3.0.8

**Comment by McJty** [comment]
So what machines are you trying? Can you show a screenshot?

**Comment by Mohawk1025** [comment]
> So what machines are you trying? Can you show a screenshot?

I've tried several, including the infuser itself, the builder, the transporters. Here's a screenshot where I'm trying to put the builder into the slot. It doesn't go, like it's incompatible. I can load dimensional shards in no problem. I just can't put any machines in.


![Minecraft_ 1 18 2 6_9_2022 9_04_12 AM](https://user-images.githubusercontent.com/59582850/172853847-b5195744-2451-45de-bc4b-09680dc5fc7b.png)
.

**Comment by echilda** [comment]
Having the same issue with the builder. Just wont go in the slot.

RFToolsBase 1.18-3.0.8
RFToolsBuilder 1.18-4.0.12

**Comment by Mohawk1025** [comment]
> Having the same issue with the builder. Just wont go in the slot.
> 
> RFToolsBase 1.18-3.0.8 RFToolsBuilder 1.18-4.0.12

Just the builder? I can't get any machine to go in. I've tried several.

**Comment by echilda** [comment]
> > Having the same issue with the builder. Just wont go in the slot.
> > RFToolsBase 1.18-3.0.8 RFToolsBuilder 1.18-4.0.12
> 
> Just the builder? I can't get any machine to go in. I've tried several.

I've only been able to make the builder so far in the pack I am using. I will update if\when I build other RFTools machines

**Comment by McJty** [comment]
I can reproduce it. Going to fix it soon

**Comment by McJty** [comment]
Fixed

**Comment by Mohawk1025** [comment]
> Fixed

Hooray! For those of us playing on a modpack, do we need to download and install the update individually?
