### ISSUE TITLE
Builder only accepting 20,000 FE/t from any one side

### ISSUE THREAD

**Issue by Nevrai** [McJtyMods/RFToolsBase#81]
My RFTools builder is only accepting 20,000 Forge energy per tick at a time on any one side, despite the fact that I’m able to output over 50 million FE/t. I had to use two flux points on the builder, and after infusing it, it started using so much energy that I had to put _five_ flux points on the builder: one on every face except the top, removing my ability to toggle it with redstone. The energy all comes from the same source, but the builder, for some reason, only accepts 20,000 FE/t from any one side.

![Builder bug](https://user-images.githubusercontent.com/59761487/185631198-fd170145-fe23-4c4f-809b-f41ae2d35c6c.png)

This isn’t an issue with Flux Networks as I also tried to input power from a Mekanism energy cube with a max output of over 100,000 FE/t, but the builder still only receives 20,000 FE/t.

Additionally to this bug, I want to ask why the builder uses so much more power after it’s been (100%) infused when its tooltip says that it has a _reduced_ power consumption when infused?

Whilst I _am_ one version behind when it comes to RFToolsBase and RFToolsBuilder, I doubt that is relevant as there’s nothing in the newest versions’ patch notes relating to this.

Lastly, albeit trivial, the builder displays the message “Not enough power!” despite having a full energy bar.

![Builder bug 2](https://user-images.githubusercontent.com/59761487/185631962-a04adf5e-6eb6-43f3-8285-c5f93c280c0d.png)

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (0.4.25)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **RFToolsBase:** 3.0.9
* **RFToolsBuilder:** 40.0.13

**Comment by McJty** [comment]
That's intentional

**Comment by Nevrai** [comment]
@McJty Oh, okay. Could you explain? Are you supposed to pipe in energy into each face of the block except the top for output? If so, how are you supposed to toggle it with redstone when every face is occupied?

Also, what about the builder using more energy after infusion? Is the tooltip, which says that it has a lower power consumption when infused, wrong? And the builder saying it doesn’t have enough power when its power is full must be a bug, I imagine.

**Comment by McJty** [comment]
Well it's a limit built in. The Builder is already powerful enough and giving it not enough power doesn't prevent it from working. It just makes it slower. And yes, if you want to speed it up a bit more give it power on all sides that are free. Also you don't actually need to use redstone to turn it on. You can also turn it on with the gui.

The builder uses less energy after infusing. Not more. I don't know how you come to the conclusion that it uses more power?

**Comment by Nevrai** [comment]
I was able to power the builder with two flux points before infusing, and it was always at full power. After infusing it, all the power was drained, and I wasn’t able to power it. I then had to add three more flux points, each supplying 20,000 FE/t, just to be able to run it sufficiently.

So clearly it does use more power after infusion. Might that be a bug?

**Comment by McJty** [comment]
I'm pretty sure it doesn't. Just tested it. What is likely happening is due to the reduced power consumption it manages to actually mine blocks faster and thus starts draining power faster

**Comment by Nevrai** [comment]
It’s a bit odd that it still doesn’t run with full power even with _five_ flux points each providing 20k FE/t. It still runs, but it says “Not enough power,” and the power bar constantly drops.

I feel like maybe this is something that should be changed. Maybe you can just make it accept 40k FE/t per side, instead of 20, perhaps when it’s infused. It seems odd that it can’t run without dropping in power even when you have more than enough energy to power it and are powering it from five different sides of the block. This also prevents you from toggling it on and off with a redstone signal, which is useful to use with redstone transmitters and receivers.

The same issue happens with the crafter. I’m not sure if this is a bug, but the RFTools tier 3 crafter only seems to accept 500 FE/t from each side, meaning even when powering it from three different sides of the block, it still won’t run when tick-boosting it using the [time in a bottle](https://www.curseforge.com/minecraft/mc-mods/time-in-a-bottle-standalone).

I don’t know. Seems like an odd decision to cap energy intake at such low amounts, especially when the builder uses so much power when quarrying. And 500 FE/t per side for the tier 3 crafter seems strangely low. Sure, that one runs fine, but you can’t really tick-boost it without it not having enough power to run efficiently.

**Comment by McJty** [comment]
Well you can configure it to accept more. That's a config option.

The low energy intake is for balancing reasons. RFTools Machines are already pretty OP. Setting power limits helps with this. But you can configure it anyway you want

**Comment by Nevrai** [comment]
Oh, my bad. Didn’t see that option. That’s nice!
