### ISSUE TITLE
Dialing device cannot be infused

### ISSUE THREAD

**Issue by Nevrai** [McJtyMods/RFToolsBase#82]
The dialing device mentions an infusing bonus in its tooltip, but it cannot be infused in the machine infuser. It’s not possible to place it in the infusion slot. I am able to infuse other machines just fine.

### Versions
* **Modpack:** [All the Mods 7](https://www.curseforge.com/minecraft/modpacks/all-the-mods-7) (0.4.26—latest)
* **Minecraft:** 1.18.2
* **Forge:** 40.1.68
* **RFToolsBase:** 3.0.10 (latest for 1.18.2)

**Comment by McJty** [comment]
Fixed next release

**Comment by Nevrai** [comment]
Sweet!
