### ISSUE TITLE
Please backport Patchouli JSON fixes from 1.19 -> 1.18

### ISSUE THREAD

**Issue by andrewsf** [McJtyMods/RFToolsBase#85]
Filing here because it concerns many/all RFTools mods.

# Issue description

None of the RFTools mods' books are valid in 1.18.

All the Patchouli `book.json` files are malformed (missing a required property), which causes errors to be thrown at server startup, and the books are unavailable to use in the game. This was already fixed in the 1.19 branches:

* rftoolsbuilder: [1887a5bd607ee397a6125d2e43a441cf7a08069e](https://github.com/McJtyMods/RFToolsBuilder/commit/1887a5bd607ee397a6125d2e43a441cf7a08069e)
* rftoolscontrol: [f64939bb279155c7ac9d06e015843fb4cb408561](https://github.com/McJtyMods/RFToolsControl/commit/f64939bb279155c7ac9d06e015843fb4cb408561)
* rftoolsdim: [75a5c9e832f406fb7546978b7adff0ebd2a9229b](https://github.com/McJtyMods/RFToolsDimensions/commit/75a5c9e832f406fb7546978b7adff0ebd2a9229b)
* rftoolspower: [483e7c1d86aa363e7703657d1c0f6c764175e685](https://github.com/McJtyMods/RFToolsPower/commit/483e7c1d86aa363e7703657d1c0f6c764175e685)
* rftoolsstorage: [9020c9a04512df3b080c1a7ecba31b6b5b8ede43](https://github.com/McJtyMods/RFToolsStorage/commit/9020c9a04512df3b080c1a7ecba31b6b5b8ede43)
* rftoolsutility: [b188ca2c799eeef3abbff1dbf45fdae3cf207419](https://github.com/McJtyMods/RFToolsUtility/commit/b188ca2c799eeef3abbff1dbf45fdae3cf207419)

Each fix should be 1 line and would expose mod documentation to a ton of players. Please backport this.

**Comment by McJty** [comment]
Thanks for the detailed report. I fixed all of them now. Note that you forgot XNet and Deep Resonance. I fixed those too
