### ISSUE TITLE
[Bug] Dim shard ore drops incorrect

### ISSUE THREAD

**Issue by AlienXtream** [McJtyMods/RFToolsBase#92]
recent update broke shard drops for me. mining the block drops the block itself but with shard's drop rates, allowing duplication too. its not silk touch, im no that dumb (i hope XD). additionally alternative means of converting to shard (smelting) is nolonger working. 

![image](https://user-images.githubusercontent.com/12606809/213978489-3ad1e43e-2e4d-41d1-8cc8-4d5d73140d54.png)

**Comment by McJty** [comment]
Version?

**Comment by AlienXtream** [comment]
frtoolsbase-1.19.1-4.1.0

**Comment by McJty** [comment]
yes but what version of Minecraft? 1.19.2 or 1.19.3?

**Comment by AlienXtream** [comment]
oh. 1.19.2. didn't realise you had any other current versions.

**Comment by McJty** [comment]
Well my mod works on both versions but I need to know which one you're using

**Comment by McJty** [comment]
I'll check it out

**Comment by McJty** [comment]
Fixed
