### ISSUE TITLE
error starting

### ISSUE THREAD

**Issue by Bobby99as** [McJtyMods/RFToolsBase#95]
I keep getting 
FF ToolsBase (rftoolsbase) has failed to load correctly
'void
mojty.rftoolsbase.setup.ModSetup.createTabljava.lang.String, java.util.function.Supplier)"
java.lang.NoSuchMethodError

I tried all 1.19.2  versions of the mod

[crash-2023-02-27_00.48.39-fml.txt](https://github.com/McJtyMods/RFToolsBase/files/10837729/crash-2023-02-27_00.48.39-fml.txt)

**Comment by McJty** [comment]
What version of mcjtylib?

**Comment by Bobby99as** [comment]
> What version of mcjtylib?

1.19-7.1.5

I also tried removeing it and got the same thing

**Comment by McJty** [comment]
Your rftoolsbase is too old. You should use 1.19.1-4.1.4

**Comment by Bobby99as** [comment]
> Your rftoolsbase is too old. You should use 1.19.1-4.1.4

As I said I tried all 1.19.2 versions of the mod

**Comment by McJty** [comment]
1.19.1-4.1.4 is for 1.19.2

**Comment by McJty** [comment]
![image](https://user-images.githubusercontent.com/8188472/221523746-32bccea9-c3ef-4c97-be92-c1e12d459094.png)

**Comment by Bobby99as** [comment]
Thanks it works
